server:
  context-path: /uaa
  port: 8554
#JACKSON
spring:
  application:
      name: uaa-server
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_example
    initialize: false
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework:
      security: DEBUG
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

eureka:
  instance:
    hostname: uaa-server
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://10.97.0.106:8761/eureka/
    healthcheck:
      enabled: true