server:
  context-path:
  port: 8554
#JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_example
    initialize: true
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework:
      security: DEBUG
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh